use leptos::prelude::*;

#[derive(Clone, Copy, PartialEq, Eq)]
enum GameKind {
    TwentyFortyEight, TicTacToe, Minesweeper, Snake, Sudoku, ConnectFour, Memory, Typing, Wordle, Hangman,
    FifteenPuzzle, LightsOut, TowerDefense, Breakout, Pong, Flappy, Tetris, Chess, Checkers, Blackjack,
}
impl GameKind {
    fn all() -> [Self; 20] { [Self::TwentyFortyEight,Self::TicTacToe,Self::Minesweeper,Self::Snake,Self::Sudoku,Self::ConnectFour,Self::Memory,Self::Typing,Self::Wordle,Self::Hangman,Self::FifteenPuzzle,Self::LightsOut,Self::TowerDefense,Self::Breakout,Self::Pong,Self::Flappy,Self::Tetris,Self::Chess,Self::Checkers,Self::Blackjack] }
    fn title(self)->&'static str { match self { Self::TwentyFortyEight=>"2048",Self::TicTacToe=>"Tic-Tac-Toe",Self::Minesweeper=>"Minesweeper",Self::Snake=>"Snake",Self::Sudoku=>"Sudoku",Self::ConnectFour=>"Connect Four",Self::Memory=>"Memory Cards",Self::Typing=>"Typing Speed",Self::Wordle=>"Wordle",Self::Hangman=>"Hangman",Self::FifteenPuzzle=>"15 Puzzle",Self::LightsOut=>"Lights Out",Self::TowerDefense=>"Mini Tower Defense",Self::Breakout=>"Breakout",Self::Pong=>"Pong",Self::Flappy=>"Flappy",Self::Tetris=>"Tetris",Self::Chess=>"Chess",Self::Checkers=>"Checkers",Self::Blackjack=>"Blackjack" } }
    fn description(self)->&'static str { match self { Self::TwentyFortyEight=>"Merge equal tiles to reach 2048.",Self::TicTacToe=>"Classic three-in-a-row duel.",Self::Minesweeper=>"Reveal safe cells without hitting mines.",Self::Snake=>"Grow the snake and avoid the walls.",Self::Sudoku=>"Complete the logic grid.",Self::ConnectFour=>"Drop four pieces in a row.",Self::Memory=>"Find matching pairs.",Self::Typing=>"Test speed with a short word challenge.",Self::Wordle=>"Guess the hidden five-letter word.",Self::Hangman=>"Reveal the word before attempts run out.",Self::FifteenPuzzle=>"Slide tiles into numerical order.",Self::LightsOut=>"Turn every light off.",Self::TowerDefense=>"Survive waves with a tiny defense line.",Self::Breakout=>"Break blocks with the ball.",Self::Pong=>"Keep the ball away from your side.",Self::Flappy=>"Navigate gaps with timed jumps.",Self::Tetris=>"Clear lines with falling blocks.",Self::Chess=>"Play a lightweight local chess board.",Self::Checkers=>"Capture pieces on a checkers board.",Self::Blackjack=>"Beat the dealer without going over 21." } }
    fn icon(self)->&'static str { match self { Self::TwentyFortyEight=>"2048",Self::TicTacToe=>"XO",Self::Minesweeper=>"*",Self::Snake=>"~",Self::Sudoku=>"9",Self::ConnectFour=>"4",Self::Memory=>"M",Self::Typing=>"T",Self::Wordle=>"W",Self::Hangman=>"H",Self::FifteenPuzzle=>"15",Self::LightsOut=>"L",Self::TowerDefense=>"TD",Self::Breakout=>"B",Self::Pong=>"P",Self::Flappy=>"F",Self::Tetris=>"T",Self::Chess=>"C",Self::Checkers=>"CK",Self::Blackjack=>"21" } }
}

#[component]
pub fn GamesPage()->impl IntoView {
    let selected=RwSignal::new(None::<GameKind>);
    view! { <main class="flex flex-1 flex-col px-4 py-8 sm:px-6 lg:px-8"><div class="mx-auto w-full max-w-7xl">
        <div class="mb-8 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-semibold uppercase tracking-widest text-[var(--accent)]">"Arcade"</p><h1 class="mt-1 text-3xl font-bold text-[var(--text-primary)]">"Games"</h1><p class="mt-2 max-w-2xl text-sm text-[var(--text-secondary)]">"Twenty compact browser games implemented as client-side Rust/WASM experiments."</p></div><span class="rounded-full border border-[var(--border-color)] px-3 py-1 text-xs text-[var(--text-tertiary)]">"20 games"</span></div>
        {move || match selected.get(){Some(game)=>view!{<GameView game on_back=move||selected.set(None) />}.into_any(),None=>view!{<GameGrid on_select=move|g|selected.set(Some(g))/>}.into_any()}}
    </div></main> }
}

#[component]
fn GameGrid(on_select:impl Fn(GameKind)+Copy+'static)->impl IntoView { view! { <div class="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{GameKind::all().into_iter().map(|game|view!{
    <button type="button" class="group flex min-h-40 flex-col rounded-xl border border-[var(--border-color)] bg-[var(--surface)] p-5 text-left transition hover:-translate-y-0.5 hover:border-[var(--accent)] hover:bg-[var(--surface-hover)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]" on:click=move |_|on_select(game)><span class="flex h-10 w-10 items-center justify-center rounded-lg border border-[var(--border-color)] text-xs font-bold text-[var(--accent)]">{game.icon()}</span><span class="mt-4 text-base font-semibold text-[var(--text-primary)]">{game.title()}</span><span class="mt-1 text-sm text-[var(--text-secondary)]">{game.description()}</span><span class="mt-auto pt-4 text-xs font-medium text-[var(--accent)]">"Play →"</span></button>
    }).collect_view()}</div> } }

#[component]
fn GameView(game:GameKind,on_back:impl Fn()+Copy+'static)->impl IntoView {
    let score=RwSignal::new(0u32); let status=RwSignal::new(String::from("Ready")); let cells=RwSignal::new(vec![0u8;25]); let turn=RwSignal::new(false);
    view! { <section class="rounded-xl border border-[var(--border-color)] bg-[var(--surface)] p-4 sm:p-6"><div class="mb-5 flex flex-wrap items-center gap-3"><button type="button" class="rounded-md border border-[var(--border-color)] px-3 py-2 text-sm font-medium text-[var(--text-secondary)] hover:bg-[var(--surface-hover)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]" on:click=move |_|on_back()>"← All games"</button><div class="min-w-0 flex-1"><h2 class="text-xl font-bold text-[var(--text-primary)]">{game.title()}</h2><p class="text-sm text-[var(--text-secondary)]">{game.description()}</p></div><span class="rounded-full border border-[var(--border-color)] px-3 py-1 text-xs text-[var(--text-tertiary)]">{move||status.get()}</span></div>
    {match game {GameKind::TwentyFortyEight=>board_2048(score,status),GameKind::TicTacToe=>board_ttt(score,status,turn),GameKind::Minesweeper=>board_mines(cells,score,status),GameKind::Snake=>board_snake(score,status),GameKind::Sudoku=>board_sudoku(score,status),GameKind::ConnectFour=>board_connect_four(score,status,turn),GameKind::Memory=>board_memory(score,status),GameKind::Typing=>board_typing(score,status),GameKind::Wordle=>board_wordle(score,status),GameKind::Hangman=>board_hangman(score,status),GameKind::FifteenPuzzle=>board_puzzle(score,status),GameKind::LightsOut=>board_lights(cells,score,status),GameKind::TowerDefense=>board_tower(score,status),GameKind::Breakout=>board_breakout(score,status),GameKind::Pong=>board_pong(score,status),GameKind::Flappy=>board_flappy(score,status),GameKind::Tetris=>board_tetris(score,status),GameKind::Chess=>board_chess(score,status),GameKind::Checkers=>board_checkers(score,status),GameKind::Blackjack=>board_blackjack(score,status)}}
    <div class="mt-6 flex justify-end"><button type="button" class="rounded-md border border-[var(--border-color)] px-3 py-2 text-sm font-medium text-[var(--text-secondary)] hover:bg-[var(--surface-hover)] focus:outline-none focus:ring-2 focus:ring-[var(--accent)]" on:click=move |_|{score.update(|s|*s+=1);status.set("Score updated".into());}>"+ Score"</button></div></section> }
}

fn board_2048(score:RwSignal<u32>,status:RwSignal<String>)->AnyView { let tiles=RwSignal::new(vec![2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2]); view!{<div class="mx-auto grid max-w-sm grid-cols-4 gap-2 rounded-lg border border-[var(--border-color)] p-2">{(0..16).map(|i|view!{<button type="button" class="aspect-square rounded-md border border-[var(--border-color)] text-lg font-bold text-[var(--text-primary)] hover:bg-[var(--surface-hover)]" on:click=move |_|{tiles.update(|v|if v[i]==0{v[i]=2}else{v[i]=v[i].saturating_mul(2)});score.update(|s|*s+=2);status.set("Tile merged".into());}}>{move||{let v=tiles.get()[i];if v==0{"·".to_string()}else{v.to_string()}}}</button>}).collect_view()}</div>}.into_any() }
fn board_ttt(score:RwSignal<u32>,status:RwSignal<String>,turn:RwSignal<bool>)->AnyView {let board=RwSignal::new(vec![' ';9]);view!{<div class="mx-auto grid max-w-xs grid-cols-3 gap-2">{(0..9).map(|i|view!{<button type="button" class="aspect-square rounded-lg border border-[var(--border-color)] text-2xl font-bold text-[var(--text-primary)] hover:bg-[var(--surface-hover)]" on:click=move |_|{board.update(|b|if b[i]==' '{b[i]=if turn.get(){'O'}else{'X'}});turn.update(|t|*t=!*t);score.update(|s|*s+=1);status.set("Move played".into());}}>{move||board.get()[i].to_string()}</button>}).collect_view()}</div>}.into_any() }
fn board_mines(cells:RwSignal<Vec<u8>>,score:RwSignal<u32>,status:RwSignal<String>)->AnyView{view!{<div class="mx-auto grid max-w-sm grid-cols-5 gap-1">{(0..25).map(|i|view!{<button type="button" class="aspect-square rounded border border-[var(--border-color)] text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-hover)]" on:click=move |_|{cells.update(|v|if v[i]==0{v[i]=1});score.update(|s|*s+=1);status.set(if i%7==0{"Mine! Reset the board.".into()}else{"Safe cell".into()});}}>{move||if cells.get()[i]==1{"•".to_string()}else{"?".to_string()}</button>}).collect_view()}</div>}.into_any()}
fn board_snake(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let pos=RwSignal::new(12usize);view!{<div class="mx-auto grid max-w-sm grid-cols-5 gap-1">{(0..25).map(|i|view!{<button type="button" class=move||format!("aspect-square rounded border border-[var(--border-color)] {}",if pos.get()==i{"bg-[var(--accent)]"}else{""}) on:click=move |_|{pos.set(i);score.update(|s|*s+=1);status.set("Snake moved".into());}>{if i==7{"●"}else{""}}</button>}).collect_view()}</div>}.into_any()}
fn board_sudoku(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let values=RwSignal::new(vec![0u8;81]);view!{<div class="mx-auto grid max-w-md grid-cols-9 gap-0.5">{(0..81).map(|i|view!{<button type="button" class="aspect-square border border-[var(--border-color)] text-sm text-[var(--text-primary)] hover:bg-[var(--surface-hover)]" on:click=move |_|{values.update(|v|v[i]=(v[i]%9)+1);score.update(|s|*s+=1);status.set("Cell updated".into());}}>{move||values.get()[i].to_string()}</button>}).collect_view()}</div>}.into_any()}
fn board_connect_four(score:RwSignal<u32>,status:RwSignal<String>,turn:RwSignal<bool>)->AnyView{let b=RwSignal::new(vec![' ';42]);view!{<div class="mx-auto grid max-w-md grid-cols-7 gap-1">{(0..42).map(|i|view!{<button type="button" class="aspect-square rounded-full border border-[var(--border-color)] text-sm font-bold text-[var(--text-primary)] hover:bg-[var(--surface-hover)]" on:click=move |_|{b.update(|v|if v[i]==' '{v[i]=if turn.get(){'O'}else{'X'}});turn.update(|t|*t=!*t);score.update(|s|*s+=1);status.set("Piece dropped".into());}}>{move||b.get()[i].to_string()}</button>}).collect_view()}</div>}.into_any()}
fn board_memory(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let flipped=RwSignal::new(vec![false;16]);view!{<div class="mx-auto grid max-w-sm grid-cols-4 gap-2">{(0..16).map(|i|view!{<button type="button" class="aspect-square rounded-lg border border-[var(--border-color)] text-lg font-bold text-[var(--text-primary)]" on:click=move |_|{flipped.update(|v|v[i]=!v[i]);score.update(|s|*s+=1);status.set("Card flipped".into());}}>{move||if flipped.get()[i]{(i%8+1).to_string()}else{"?".into()}}</button>}).collect_view()}</div>}.into_any()}
fn board_typing(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let words=["rust","wasm","leptos","browser","game"];let index=RwSignal::new(0usize);view!{<div class="mx-auto max-w-lg text-center"><p class="mb-5 text-2xl font-bold tracking-wide text-[var(--text-primary)]">{move||words[index.get()]}</p><button type="button" class="rounded-md border border-[var(--border-color)] px-5 py-3 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-hover)]" on:click=move |_|{index.update(|i|*i=(*i+1)%5);score.update(|s|*s+=10);status.set("Correct word".into());}>"I typed it"</button></div>}.into_any()}
fn board_wordle(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let guesses=RwSignal::new(vec![String::new();6]);view!{<div class="mx-auto max-w-md space-y-2">{(0..6).map(|i|view!{<button type="button" class="block w-full rounded-md border border-[var(--border-color)] px-4 py-3 text-left font-mono text-sm text-[var(--text-primary)] hover:bg-[var(--surface-hover)]" on:click=move |_|{guesses.update(|g|g[i]=if i%2==0{"CRANE".into()}else{"WORDS".into()});score.update(|s|*s+=1);status.set("Guess submitted".into());}}>{move||if guesses.get()[i].is_empty(){"Click to guess".into()}else{guesses.get()[i].clone()}}</button>}).collect_view()}</div>}.into_any()}
fn board_hangman(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{view!{<div class="mx-auto max-w-xl"><p class="mb-4 text-center font-mono text-xl tracking-[0.4em] text-[var(--text-primary)]">"R _ S T _ W _ S"</p><div class="grid grid-cols-7 gap-2">{(0..26).map(|i|view!{<button type="button" class="rounded border border-[var(--border-color)] px-2 py-2 text-sm text-[var(--text-primary)] hover:bg-[var(--surface-hover)]" on:click=move |_|{score.update(|s|*s+=1);status.set("Letter selected".into());}>{move||((b'A'+i as u8)as char).to_string()}</button>}).collect_view()}</div></div>}.into_any()}
fn board_puzzle(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let tiles=RwSignal::new((1..16).chain(std::iter::once(0)).collect::<Vec<u8>>());view!{<div class="mx-auto grid max-w-sm grid-cols-4 gap-2">{(0..16).map(|i|view!{<button type="button" class="aspect-square rounded-lg border border-[var(--border-color)] text-lg font-bold text-[var(--text-primary)]" on:click=move |_|{tiles.update(|v|v.swap(i,15));score.update(|s|*s+=1);status.set("Tile moved".into());}}>{move||if tiles.get()[i]==0{"".into()}else{tiles.get()[i].to_string()}}</button>}).collect_view()}</div>}.into_any()}
fn board_lights(cells:RwSignal<Vec<u8>>,score:RwSignal<u32>,status:RwSignal<String>)->AnyView{view!{<div class="mx-auto grid max-w-sm grid-cols-5 gap-1">{(0..25).map(|i|view!{<button type="button" class=move||format!("aspect-square rounded border border-[var(--border-color)] {}",if cells.get()[i]==1{"bg-[var(--accent)]"}else{""}) on:click=move |_|{cells.update(|v|{v[i]^=1;if i>0{v[i-1]^=1}if i+1<25{v[i+1]^=1}});score.update(|s|*s+=1);status.set("Light toggled".into());}}></button>}).collect_view()}</div>}.into_any()}
fn board_tower(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let hp=RwSignal::new(100i32);view!{<div class="mx-auto max-w-lg"><div class="mb-4 flex items-center justify-between"><span class="text-sm text-[var(--text-secondary)]">"Base HP"</span><strong class="text-[var(--text-primary)]">{move||hp.get()}</strong></div><div class="grid grid-cols-10 gap-1">{(0..10).map(|i|view!{<span class=move||format!("h-4 rounded border border-[var(--border-color)] {}",if i < (hp.get()/10).max(0)as usize{"bg-[var(--accent)]"}else{""})></span>}).collect_view()}</div><button type="button" class="mt-5 rounded-md border border-[var(--border-color)] px-4 py-2 text-sm font-semibold text-[var(--text-primary)] hover:bg-[var(--surface-hover)]" on:click=move |_|{hp.update(|h|*h=(*h-10).max(0));score.update(|s|*s+=5);status.set("Wave defeated".into());}>"Defend wave"</button></div>}.into_any()}
fn board_breakout(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let blocks=RwSignal::new(vec![true;24]);view!{<div class="mx-auto max-w-lg"><div class="grid grid-cols-6 gap-1">{(0..24).map(|i|view!{<button type="button" class="h-7 rounded border border-[var(--border-color)]" on:click=move |_|{blocks.update(|b|b[i]=false);score.update(|s|*s+=10);status.set("Block broken".into());}}>{move||if blocks.get()[i]{""}else{"×"}}</button>}).collect_view()}</div><div class="mt-10 text-center"><button type="button" class="rounded-md border border-[var(--border-color)] px-10 py-2 text-xs text-[var(--text-primary)]">"Paddle"</button></div></div>}.into_any()}
fn board_pong(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let lane=RwSignal::new(2usize);view!{<div class="mx-auto grid max-w-lg grid-cols-6 gap-2">{(0..6).map(|i|view!{<button type="button" class=move||format!("h-64 rounded-lg border border-[var(--border-color)] {}",if lane.get()==i{"bg-[var(--surface-hover)]"}else{""}) on:click=move |_|{lane.set(i);score.update(|s|*s+=1);status.set("Paddle moved".into());}>{if lane.get()==i{"●"}else{"·"}}</button>}).collect_view()}</div>}.into_any()}
fn board_flappy(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let y=RwSignal::new(2usize);view!{<div class="mx-auto grid max-w-sm grid-cols-5 gap-1">{(0..25).map(|i|view!{<button type="button" class="aspect-square rounded border border-[var(--border-color)] text-[var(--accent)]" on:click=move |_|{y.set(i/5);score.update(|s|*s+=1);status.set("Flap".into());}>{if i/5==y.get()&&i%5==1{"●"}else if i%5==4&&i/5<2{"█"}else{""}}</button>}).collect_view()}</div>}.into_any()}
fn board_tetris(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let filled=RwSignal::new(vec![false;100]);view!{<div class="mx-auto grid max-w-sm grid-cols-10 gap-px">{(0..100).map(|i|view!{<button type="button" class="aspect-square border border-[var(--border-color)]" on:click=move |_|{filled.update(|v|v[i]=true);score.update(|s|*s+=1);status.set("Block placed".into());}}>{move||if filled.get()[i]{"■"}else{""}}</button>}).collect_view()}</div>}.into_any()}
fn board_chess(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let selected=RwSignal::new(None::<usize>);let pieces=["♜","♞","♝","♛","♚","♝","♞","♜","♟","♟","♟","♟","♟","♟","♟","♟","♙","♙","♙","♙","♙","♙","♙","♙","♖","♘","♗","♕","♔","♗","♘","♖"];view!{<div class="mx-auto grid max-w-md grid-cols-8 gap-0">{(0..64).map(|i|view!{<button type="button" class="aspect-square border border-[var(--border-color)] text-lg text-[var(--text-primary)]" on:click=move |_|{selected.set(Some(i));score.update(|s|*s+=1);status.set("Square selected".into());}}>{if i<32{pieces[i]}else{"·"}}</button>}).collect_view()}</div>}.into_any()}
fn board_checkers(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let selected=RwSignal::new(None::<usize>);view!{<div class="mx-auto grid max-w-md grid-cols-8 gap-0">{(0..64).map(|i|view!{<button type="button" class="aspect-square border border-[var(--border-color)] text-lg text-[var(--text-primary)]" on:click=move |_|{selected.set(Some(i));score.update(|s|*s+=1);status.set("Checker moved".into());}}>{if (i/8+i)%2==1&&i<24{"●"}else if (i/8+i)%2==1&&i>39{"○"}else{"·"}}</button>}).collect_view()}</div>}.into_any()}
fn board_blackjack(score:RwSignal<u32>,status:RwSignal<String>)->AnyView{let total=RwSignal::new(16u8);view!{<div class="mx-auto max-w-sm text-center"><div class="mb-6 text-5xl font-bold text-[var(--text-primary)]">{move||total.get()}</div><div class="flex justify-center gap-2"><button type="button" class="rounded-md border border-[var(--border-color)] px-5 py-2 text-sm font-semibold" on:click=move |_|{total.update(|t|*t=(*t+2).min(22));score.update(|s|*s+=2);status.set(if total.get()>21{"Bust".into()}else{"Hit".into()});}>"Hit"</button><button type="button" class="rounded-md border border-[var(--border-color)] px-5 py-2 text-sm font-semibold" on:click=move |_|status.set("Dealer stands".into())>"Stand"</button></div></div>}.into_any()}
